name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.0.4
publish_to: Alberto Luna forked

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_serializable: ^1.1.0

  signature: ^5.4.0
  rxdart: ^0.27.7
  json_annotation: ^4.8.0
  audiofileplayer: ^2.1.1

# Overriding carp core libraries to use the local copy
# Remove this before release of package
dependency_overrides:
  # carp_serializable:
  #   path: ../carp/carp.sensing-flutter/carp_serializable/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  flutter_lints: any
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lang/
    - assets/audio/

# auto generate json code (.g files) with:
#   dart run build_runner build --delete-conflicting-outputs
